#!/usr/bin/env python3
"""
build_proposal.py — Assemble final PROPOSAL HTML from skeleton + tab contents.

Usage:
    python3 tools/build_proposal.py \
        --deal-id 560 \
        --title "Analyse strategique · Biscuiterie Mere Poulard" \
        --diagnostic /tmp/tab_diagnostic.html \
        --strategie /tmp/tab_strategie.html \
        --investissement /tmp/tab_investissement.html \
        --cas-clients /tmp/tab_cas_clients.html \
        [--extra-js /tmp/extra_roi_sim.js] \
        [--output .cache/deals/560/artifacts/PROPOSAL-20260302-biscuiterie.html]

The skeleton (templates/proposal-skeleton.html) contains the full CSS, JS, nav,
and page structure. This script replaces the {{PLACEHOLDERS}} with the actual
tab content generated by the AI.

Exit codes: 0=OK, 1=usage error, 2=file not found, 3=assembly error
"""

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path


def read_file(path):
    """Read file content, return string."""
    p = Path(path)
    if not p.exists():
        print(f"[ERROR] File not found: {path}", file=sys.stderr)
        sys.exit(2)
    return p.read_text(encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Assemble PROPOSAL HTML from skeleton + tabs")
    parser.add_argument("--deal-id", required=True, help="Deal ID")
    parser.add_argument("--title", required=True, help="Page title (visible in browser tab)")
    parser.add_argument("--diagnostic", required=True, help="Path to diagnostic tab HTML fragment")
    parser.add_argument("--strategie", required=True, help="Path to strategie tab HTML fragment")
    parser.add_argument("--investissement", required=True, help="Path to investissement tab HTML fragment")
    parser.add_argument("--cas-clients", required=True, help="Path to cas-clients tab HTML fragment")
    parser.add_argument("--extra-js", default=None, help="Path to extra JS (ROI simulator custom logic)")
    parser.add_argument("--output", default=None, help="Output path (default: .cache/deals/{deal_id}/artifacts/PROPOSAL-{date}-proposal.html)")
    args = parser.parse_args()

    # Locate skeleton
    script_dir = Path(__file__).parent.parent
    skeleton_path = script_dir / "templates" / "proposal-skeleton.html"
    if not skeleton_path.exists():
        print(f"[ERROR] Skeleton not found: {skeleton_path}", file=sys.stderr)
        sys.exit(2)

    skeleton = skeleton_path.read_text(encoding="utf-8")

    # Read tab contents
    tab_diagnostic = read_file(args.diagnostic)
    tab_strategie = read_file(args.strategie)
    tab_investissement = read_file(args.investissement)
    tab_cas_clients = read_file(args.cas_clients)

    # Read extra JS (optional)
    extra_js = ""
    if args.extra_js:
        extra_js = read_file(args.extra_js)

    # Assemble
    html = skeleton
    html = html.replace("{{TITLE}}", args.title)
    html = html.replace("{{TAB_DIAGNOSTIC}}", tab_diagnostic)
    html = html.replace("{{TAB_STRATEGIE}}", tab_strategie)
    html = html.replace("{{TAB_INVESTISSEMENT}}", tab_investissement)
    html = html.replace("{{TAB_CAS_CLIENTS}}", tab_cas_clients)
    html = html.replace("{{EXTRA_JS}}", extra_js)

    # Verify no unreplaced placeholders remain
    import re
    remaining = re.findall(r'\{\{[A-Z_]+\}\}', html)
    if remaining:
        print(f"[ERROR] Unreplaced placeholders: {remaining}", file=sys.stderr)
        sys.exit(3)

    # Determine output path
    if args.output:
        output_path = Path(args.output)
    else:
        date_str = datetime.now().strftime("%Y%m%d")
        cache_dir = script_dir / ".cache" / "deals" / args.deal_id / "artifacts"
        cache_dir.mkdir(parents=True, exist_ok=True)
        output_path = cache_dir / f"PROPOSAL-{date_str}-proposal.html"

    # Ensure parent directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write output
    output_path.write_text(html, encoding="utf-8")

    # Summary to stdout (JSON for agent consumption)
    import json
    summary = {
        "status": "ok",
        "output_path": str(output_path),
        "size_bytes": len(html.encode("utf-8")),
        "tabs": {
            "diagnostic": len(tab_diagnostic),
            "strategie": len(tab_strategie),
            "investissement": len(tab_investissement),
            "cas_clients": len(tab_cas_clients),
        },
        "extra_js": bool(extra_js),
    }
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
