#!/usr/bin/env python3
"""
build_proposal.py — Assemble final PROPOSAL HTML from skeleton + tab contents.

Usage:
    python3 tools/build_proposal.py \
        --deal-id 560 \
        --title "Analyse strategique · Biscuiterie Mere Poulard" \
        --diagnostic /tmp/tab_diagnostic.html \
        --strategie /tmp/tab_strategie.html \
        --investissement /tmp/tab_investissement.html \
        --cas-clients /tmp/tab_cas_clients.html \
        [--extra-js /tmp/extra_roi_sim.js] \
        [--output .cache/deals/560/artifacts/PROPOSAL-20260302-biscuiterie.html]

The skeleton (templates/proposal-skeleton.html) contains the full CSS, JS, nav,
and page structure. This script replaces the {{PLACEHOLDERS}} with the actual
tab content generated by the AI.

Exit codes: 0=OK, 1=usage error, 2=file not found, 3=assembly error
"""

import argparse
import os
import re
import sys
import unicodedata
from datetime import datetime
from pathlib import Path


def slugify(text):
    """Remove accents and normalize text for use in HTML IDs and data-attributes."""
    nfkd = unicodedata.normalize('NFKD', text)
    return ''.join(c for c in nfkd if not unicodedata.combining(c))


def read_file(path):
    """Read file content, return string."""
    p = Path(path)
    if not p.exists():
        print(f"[ERROR] File not found: {path}", file=sys.stderr)
        sys.exit(2)
    return p.read_text(encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Assemble PROPOSAL HTML from skeleton + tabs")
    parser.add_argument("--deal-id", required=True, help="Deal ID")
    parser.add_argument("--title", required=True, help="Page title (visible in browser tab)")
    parser.add_argument("--contexte", default=None, help="Path to contexte tab HTML fragment (optional, adds 5th tab)")
    parser.add_argument("--diagnostic", required=True, help="Path to diagnostic tab HTML fragment")
    parser.add_argument("--strategie", required=True, help="Path to strategie tab HTML fragment")
    parser.add_argument("--investissement", required=True, help="Path to investissement tab HTML fragment")
    parser.add_argument("--projet", default=None, help="Path to projet tab HTML fragment (optional)")
    parser.add_argument("--cas-clients", default=None, help="Path to cas-clients tab HTML fragment (optional)")
    parser.add_argument("--extra-js", default=None, help="Path to extra JS (ROI simulator custom logic)")
    parser.add_argument("--output", default=None, help="Output path (default: .cache/deals/{deal_id}/artifacts/PROPOSAL-{date}-proposal.html)")
    args = parser.parse_args()

    # Locate skeleton
    script_dir = Path(__file__).parent.parent
    skeleton_path = script_dir / "templates" / "proposal-skeleton.html"
    if not skeleton_path.exists():
        print(f"[ERROR] Skeleton not found: {skeleton_path}", file=sys.stderr)
        sys.exit(2)

    skeleton = skeleton_path.read_text(encoding="utf-8")

    # Read tab contents
    tab_contexte = read_file(args.contexte) if args.contexte else None
    tab_diagnostic = read_file(args.diagnostic)
    tab_strategie = read_file(args.strategie)
    tab_investissement = read_file(args.investissement)
    tab_projet = read_file(args.projet) if args.projet else None
    tab_cas_clients = read_file(args.cas_clients) if args.cas_clients else None

    # Read extra JS (optional)
    extra_js = ""
    if args.extra_js:
        extra_js = read_file(args.extra_js)

    # Assemble
    html = skeleton
    html = html.replace("{{TITLE}}", args.title)

    # Inject Contexte tab if provided (before Diagnostic in nav + content)
    if tab_contexte:
        # Add Contexte nav button before Diagnostic, make it active
        html = html.replace(
            '<button class="nav-tab active" data-tab="diagnostic">Diagnostic</button>',
            '<button class="nav-tab active" data-tab="contexte">Contexte</button>'
            '<button class="nav-tab" data-tab="diagnostic">Diagnostic</button>'
        )
        # Add Contexte tab content before Diagnostic, make it active
        contexte_block = (
            '<!-- ONGLET 0 : CONTEXTE -->\n'
            '<div id="tab-contexte" class="tab-content active">\n'
            f'{tab_contexte}\n'
            '</div>\n\n'
        )
        html = html.replace(
            '<!-- ONGLET 1 : DIAGNOSTIC -->\n'
            '<div id="tab-diagnostic" class="tab-content active">',
            contexte_block +
            '<!-- ONGLET 1 : DIAGNOSTIC -->\n'
            '<div id="tab-diagnostic" class="tab-content">'
        )

    html = html.replace("{{TAB_DIAGNOSTIC}}", tab_diagnostic)
    html = html.replace("{{TAB_STRATEGIE}}", tab_strategie)
    html = html.replace("{{TAB_INVESTISSEMENT}}", tab_investissement)

    # Inject Projet tab if provided, otherwise remove placeholder and nav button
    if tab_projet:
        html = html.replace("{{TAB_PROJET}}", tab_projet)
    else:
        # Remove Projet nav button
        html = html.replace(
            '    <button class="nav-tab" data-tab="projet">Projet</button>\n', ''
        )
        # Remove Projet tab-content block
        html = html.replace(
            '<!-- ONGLET 4 : PROJET -->\n'
            '<div id="tab-projet" class="tab-content">\n'
            '{{TAB_PROJET}}\n'
            '</div>\n\n', ''
        )

    # Inject Cas clients tab if provided, otherwise remove placeholder and nav button
    if tab_cas_clients:
        html = html.replace("{{TAB_CAS_CLIENTS}}", tab_cas_clients)
    else:
        # Remove Cas clients nav button
        html = html.replace(
            '    <button class="nav-tab" data-tab="cas-clients">Cas clients</button>\n', ''
        )
        # Remove Cas clients tab-content block
        html = html.replace(
            '<!-- ONGLET 5 : CAS CLIENTS -->\n'
            '<div id="tab-cas-clients" class="tab-content">\n'
            '{{TAB_CAS_CLIENTS}}\n'
            '</div>\n', ''
        )
    html = html.replace("{{EXTRA_JS}}", extra_js)

    # Slugify all tab IDs and data-tab attributes (remove accents)
    # Matches id="tab-xxx" and data-tab="xxx"
    def slugify_match(m):
        return m.group(0)[:m.start(1) - m.start(0)] + slugify(m.group(1)) + m.group(0)[m.end(1) - m.start(0):]
    html = re.sub(r'id="(tab-[^"]+)"', lambda m: f'id="{slugify(m.group(1))}"', html)
    html = re.sub(r'data-tab="([^"]+)"', lambda m: f'data-tab="{slugify(m.group(1))}"', html)
    # Also fix getElementById calls in onclick handlers
    html = re.sub(r"getElementById\('(tab-[^']+)'\)", lambda m: f"getElementById('{slugify(m.group(1))}')", html)
    html = re.sub(r"querySelector\('\[data-tab=([^\]]+)\]'\)", lambda m: f"querySelector('[data-tab={slugify(m.group(1))}]')", html)

    # Verify no unreplaced placeholders remain
    remaining = re.findall(r'\{\{[A-Z_]+\}\}', html)
    if remaining:
        print(f"[ERROR] Unreplaced placeholders: {remaining}", file=sys.stderr)
        sys.exit(3)

    # Determine output path
    if args.output:
        output_path = Path(args.output)
    else:
        date_str = datetime.now().strftime("%Y%m%d")
        cache_dir = script_dir / ".cache" / "deals" / args.deal_id / "artifacts"
        cache_dir.mkdir(parents=True, exist_ok=True)
        output_path = cache_dir / f"PROPOSAL-{date_str}-proposal.html"

    # Ensure parent directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Versioning: if output file already exists, archive it as -v{N}
    if output_path.exists():
        import glob
        base = output_path.stem
        ext = output_path.suffix
        parent = output_path.parent
        existing_versions = glob.glob(str(parent / f"{base}-v*{ext}"))
        next_version = len(existing_versions) + 1
        archive_path = parent / f"{base}-v{next_version}{ext}"
        output_path.rename(archive_path)
        print(f"[INFO] Archived previous version as {archive_path.name}", file=sys.stderr)

    # Write output
    output_path.write_text(html, encoding="utf-8")

    # Summary to stdout (JSON for agent consumption)
    import json
    summary = {
        "status": "ok",
        "output_path": str(output_path),
        "size_bytes": len(html.encode("utf-8")),
        "tabs": {
            **({"contexte": len(tab_contexte)} if tab_contexte else {}),
            "diagnostic": len(tab_diagnostic),
            "strategie": len(tab_strategie),
            "investissement": len(tab_investissement),
            **({"projet": len(tab_projet)} if tab_projet else {}),
            **({"cas_clients": len(tab_cas_clients)} if tab_cas_clients else {}),
        },
        "extra_js": bool(extra_js),
    }
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
